import type { Metadata } from "next";

import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";



export const metadata: Metadata = {
  title: "emlak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
       
        <AuthProvider> 
        <Navbar/>
       <div className="flex flex-col min-h-screen">{children}</div>
        </AuthProvider>
        <Footer/>
      </body>
    </html>
  );
}
